# Generated by Django 5.2.1 on 2025-05-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_logininfo_alter_user_address_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
